FROM kallikrein/ubuntu:14.04

MAINTAINER Jan Kopacek "jan.kopacek@gmail.com"

RUN curl https://nodejs.org/dist/latest-v6.x/node-v6.10.1-linux-x64.tar.gz | tar xz -C /usr/local/ --strip=1

VOLUME /src
WORKDIR /src
